SELECT * FROM lik_operator.data_analytics;
select * from lik_operator.data_analytics where category like "%hold%";
select * from demo1.data_analytics order by Price asc;
select * from demo1.data_analytics order by Price asc,1 desc;
select * from demo1.data_analytics order by Price asc limit 3;
select * from demo1.data_analytics order by Price asc limit 2,3;
select * from demo1.data_analytics where Price between 100 and 300;
select * from demo1.data_analytics where category in("food, F","grocerry, G");
select * from demo1.data_analytics where category not in("food, F","grocerry, G");
select concat(subcategory,initials) as abhi from demo1.data_analytics;
select concat_ws("->",subcategory, initials) as abhi1 from demo1.data_analytics;
select length(subcategory)as abhi2 from demo1.data_analytics;
select upper(category) as CATEGORY_U from demo1.data_analytics;
select lower(category) as CATEGORY_U from demo1.data_analytics;
select left(category, 3) as CATEG from demo1.data_analytics;
select right(category, 3) as CATEG from demo1.data_analytics;
select mid(category, 2, 5) as CATEG from demo1.data_analytics;
select sum(price) as total from demo1.data_analytics;
select count(Price) as count_tot from demo1.data_analytics;
select avg(Price) as avge from demo1.data_analytics;
select max(Price) as maxi from demo1.data_analytics;
select min(Price) as mini from demo1.data_analytics;
select truncate(Price,0) as valued from demo1.data_analytics;
select ceil(Price) as valued from demo1.data_analytics;
select floor(Price) as valued from demo1.data_analytics;
select date(Date) as date_ from demo1.data_analytics;